name: AutomatedUpdate # Name of action

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # schedule

jobs:
  build:
    runs-on: ubuntu-latest # Build environment
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2 # Setup python
        with:
          python-version: "3.x" # Python version

      - name: Install dependencies # Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update
        run: |
          python script/fetch.py --production

      - name: Commit and Push
        run: |
          git config user.name "azu0609"
          git config user.email "ipadgoogcloud@gmail.com"
          git add .
          git commit -m "Automated update"
          git pull
          git push origin main
