name: AutomatedUpdate # Name of action

on:
  workflow_dispatch: # allow manual run
  schedule:
    - cron: '0 3 * * *' # schedule run

jobs:
  build:
    runs-on: ubuntu-latest # Set build environment
    steps: # Steps to update
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2 # Setup python
        with:
          python-version: "3.x" # Set python version

      - name: Install dependencies # Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update # Upadate (Check, replace) repo
        working-directory: ./script
        run: |
          python fetch.py --production

      - name: Commit and Push # Apply changes
        run: |
          git config user.name "azu0609"
          git config user.email "ipadgoogcloud@gmail.com"
          git add .
          git commit -m "Feat: update version - automated"
          git pull
          git push origin main
